apiVersion: orchestration.sas.com/v2beta15
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-redis-operator
    sas.com/component-version: 1.11.10-20231102.1698945202078
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/start-all-execute-phase-0: "true"
  name: start-all-execute-redis
spec:
  args:
  - name: namespace
  steps:
  - args:
    - patch
    - --namespace
    - $namespace
    - distributedredisclusters.redis.kun
    - $resource.Name
    - --type
    - json
    - --patch
    - '(print "[{\"op\":\"replace\", \"path\": \"/spec/shutdown\", \"value\":" (.LastAppliedConfigurationValue $resource "{.spec.shutdown}" "false") "}]" )'
    cmd: kubectl
    when: (.ClusterDefinitions (((.NewClusterDefinitionsIterationSpec).WithGroup "redis.kun").WithResource "distributedredisclusters"))
    withClusterResources:
      group: redis.kun
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: distributedredisclusters
